### ISSUE TITLE
Sequence of files

### ISSUE THREAD

**Issue by Chris31070** [kvsingh/lyrics-sentiment-analysis#2]
A more general question: can you give some guidance of the sequence of running the files? Thanks again!

**Comment by kvsingh** [comment]
Hi @Chris31070 

- First, you need to run songs.py to get lyrics from genuis.com. Edit line no 23 in that file to add alternative artists. I think that right now, it takes top 10 songs for each artist, to customize that, you will have to edit search.py
- Then, run clean_data.py. 
- After that, you can run text_analysis.py, sentiment.py and wordclouds.py according to your need.

Here is a [blog post](https://kvsingh.github.io/lyrics-sentiment-analysis.html) I wrote which explains the analysis. I'll try to add a readme here soon to give more details for customization.

Hope this helps :)

**Comment by Chris31070** [comment]
Great, many thanks for your reply, gonna try it again!
